# Generated by Django 4.1 on 2022-09-02 15:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Document',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('document_name', models.CharField(max_length=10)),
                ('document_details', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='Shareholders',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('shareholder_name', models.CharField(max_length=10)),
                ('share_amount', models.PositiveBigIntegerField()),
            ],
        ),
        migrations.CreateModel(
            name='Company',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cmp_name', models.CharField(max_length=10)),
                ('cmp_address', models.CharField(max_length=10)),
                ('cmp_info', models.CharField(max_length=10)),
                ('shareholders', models.ManyToManyField(to='company.shareholders')),
            ],
        ),
    ]
